
package TrabajoPOOFinal;

import java.awt.Color;
import java.io.IOException;
import javax.swing.JOptionPane;


public class FrmContactos extends javax.swing.JFrame {
    
    int  xMouse, yMouse;

    private ModeloContacto modelo;
    
    public FrmContactos() {
        initComponents();
        modelo=new ModeloContacto();
        this.tblProductos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlimp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtapellido = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelexit = new javax.swing.JPanel();
        exitxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlimp.setBackground(new java.awt.Color(0, 255, 102));
        btnlimp.setFont(new java.awt.Font("Klavika Bd", 0, 24)); // NOI18N
        btnlimp.setText("Limpiar campos");
        btnlimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/5087579 (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 130, 120));

        jLabel4.setFont(new java.awt.Font("Klavika Rg", 0, 36)); // NOI18N
        jLabel4.setText("CONTACTOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 255, 102));
        jButton3.setFont(new java.awt.Font("Klavika Bd", 0, 24)); // NOI18N
        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 255, 102));
        jButton2.setFont(new java.awt.Font("Klavika Bd", 0, 24)); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, 40));

        jButton1.setBackground(new java.awt.Color(0, 255, 102));
        jButton1.setFont(new java.awt.Font("Klavika Bd", 0, 24)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        txtapellido.setBackground(new java.awt.Color(153, 255, 255));
        txtapellido.setForeground(new java.awt.Color(204, 204, 204));
        txtapellido.setText("Apellido");
        txtapellido.setBorder(null);
        txtapellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtapellidoMousePressed(evt);
            }
        });
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 230, 20));

        txtcedula.setBackground(new java.awt.Color(153, 255, 255));
        txtcedula.setForeground(new java.awt.Color(204, 204, 204));
        txtcedula.setText("Cedula");
        txtcedula.setBorder(null);
        txtcedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcedulaMousePressed(evt);
            }
        });
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 170, -1));

        txtname.setBackground(new java.awt.Color(153, 255, 255));
        txtname.setForeground(new java.awt.Color(204, 204, 204));
        txtname.setText("Nombre");
        txtname.setBorder(null);
        txtname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnameMousePressed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 240, 30));

        jLabel3.setFont(new java.awt.Font("Klavika Bd", 1, 18)); // NOI18N
        jLabel3.setText("Cedula");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Klavika Bd", 1, 18)); // NOI18N
        jLabel2.setText("Apellido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Klavika Bd", 1, 18)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 640, 233));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 270, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 290, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 280, 10));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/unaldas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 70));

        panelexit.setBackground(new java.awt.Color(255, 51, 51));
        panelexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelexitMouseExited(evt);
            }
        });

        exitxt.setBackground(new java.awt.Color(255, 102, 102));
        exitxt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        exitxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitxt.setText("X");
        exitxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelexitLayout = new javax.swing.GroupLayout(panelexit);
        panelexit.setLayout(panelexitLayout);
        panelexitLayout.setHorizontalGroup(
            panelexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelexitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelexitLayout.setVerticalGroup(
            panelexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelexitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitxtMouseClicked

    private void panelexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelexitMouseExited
        panelexit.setBackground(Color.white);
        exitxt.setForeground(Color.red);
    }//GEN-LAST:event_panelexitMouseExited

    private void panelexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelexitMouseEntered
        panelexit.setBackground(Color.red);
        exitxt.setForeground(Color.white);
    }//GEN-LAST:event_panelexitMouseEntered

    private void panelexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_panelexitMouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xMouse =evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void txtnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMousePressed
        if(txtname.getText().equals("Nombre")){
            txtname.setText("");
            txtname.setForeground(Color.black);
        }
        if(txtapellido.getText().isEmpty()){
            txtapellido.setText("Apellido");
            txtapellido.setForeground(Color.gray);

        }
        if(txtcedula.getText().isEmpty()){
            txtcedula.setText("Cedula");
            txtcedula.setForeground(Color.gray);
        }

    }//GEN-LAST:event_txtnameMousePressed

    private void txtcedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcedulaMousePressed
        if(txtcedula.getText().equals("Cedula")){
            txtcedula.setText("");
            txtcedula.setForeground(Color.black);
        }
        if(txtapellido.getText().isEmpty()){
            txtapellido.setText("Apellido");
            txtapellido.setForeground(Color.gray);

        }
        if(txtname.getText().isEmpty()){
            txtname.setText("Nombre");
            txtname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtcedulaMousePressed

    private void txtapellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidoMousePressed
        if(txtapellido.getText().equals("Apellido")){
            txtapellido.setText("");
            txtapellido.setForeground(Color.black);
        }
        if(txtname.getText().isEmpty()){
            txtname.setText("Nombre");
            txtname.setForeground(Color.gray);

        }
        if(txtcedula.getText().isEmpty()){
            txtcedula.setText("Cedula");
            txtcedula.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtapellidoMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre= this.txtname.getText();
        String apellido = this.txtapellido.getText();
        String cedula = this.txtcedula.getText();

        Contacto p = new Contacto(nombre, apellido, cedula);
        modelo.agregarProducto(p);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int fila=this.tblProductos.getSelectedRow();
        if(fila>=0){
            modelo.eliminarProducto(fila);
             JOptionPane.showMessageDialog(null, "Se ha eliminado el contacto");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            modelo.guardarEnArchivo();
           JOptionPane.showMessageDialog(null, "Se ha guardado el archivo de texto");
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnlimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpActionPerformed
        txtname.setText("");
        txtapellido.setText("");
        txtcedula.setText("");
    }//GEN-LAST:event_btnlimpActionPerformed

    private void exitxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitxtMouseEntered
        panelexit.setBackground(Color.red);
        exitxt.setForeground(Color.white);
    }//GEN-LAST:event_exitxtMouseEntered

    private void exitxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitxtMouseExited
         panelexit.setBackground(Color.white);
        exitxt.setForeground(Color.red);
    }//GEN-LAST:event_exitxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmContactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlimp;
    private javax.swing.JLabel exitxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelexit;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
